import fs from "fs";
import path from "path";
import { rimraf } from "rimraf";
import type { DocsConfig } from "@/types/docs";

// import { getDocs } from "@/server/docs";

// const getCategoryDocs = (category: string) => {
//   return getDocs(category).map((category) => ({
//     title: category.title,
//     href: category.href,
//     label: category.label,
//     disabled: category.disabled,
//   }));
// };

const docsConfig: DocsConfig = {
  nav: [
    {
      title: "Getting Started",
      slug: "docs",
      items: [
        {
          title: "Introduction",
          href: "/docs/introduction",
        },
        {
          title: "Installation",
          href: "/docs/installation",
        },
      ],
    },
    {
      title: "Components",
      slug: "components",
      items: [
        {
          title: "Overview",
          href: "/components",
        },
        {
          title: "Animations",
          items: [
            { title: "Tag", href: "/components/animations/tag" },
          ]
        },
      ],
    },
    {
      title: "Guides",
      slug: "guides",
      items: [
        {
          title: "Getting Started",
          href: "/guides",
        },
        {
          title: "3dAnimations",
          items: [
            { title: "Tag", href: "/guides/tag" },
          ]
        },
      ],
    },
  ],
};

const index = `
// This file is autogenerated by scripts/build-preview-imports.ts
// Do not edit this file directly.
import type { DocsConfig } from "@/types/docs";

export const docsConfig: DocsConfig = ${JSON.stringify(docsConfig)};
`;

rimraf.sync(path.join(process.cwd(), "src", "config", "docs-config.ts"));
fs.writeFileSync(path.join(process.cwd(), "src", "config", "docs-config.ts"), index);

console.log("\x1b[32m✓\x1b[0m Created docs-config file.");