// This file is autogenerated by scripts/build-preview-imports.ts
// Do not edit this file directly.
import React from 'react';

export const previews = {
  'demos/components/chai/animations/tag': {
    component: React.lazy<React.FC>(
      () => import('@/lib/demos/components/chai/animations/tag')
    ),
    code: [
      {
        title: 'tag.tsx',
        code: '"use client";\r\nimport React from "react";\r\n\r\nimport Tag3d from "@/lib/components/chai/3dtag";\r\n\r\nexport default function Tagdemo() {\r\n  return (\r\n    <div className="items-center justify-center md:h-auto dark:bg-black bg-white relative w-full">\r\n    <Tag3d/>\r\n   \r\n  </div>\r\n   \r\n      \r\n   \r\n  );\r\n}\r\n',
      },
    ],
  },
};
