
// This file is autogenerated by scripts/build-preview-imports.ts
// Do not edit this file directly.
import type { DocsConfig } from "@/types/docs";

export const docsConfig: DocsConfig = {"nav":[{"title":"Getting Started","slug":"docs","items":[{"title":"Introduction","href":"/docs/introduction"},{"title":"Installation","href":"/docs/installation"}]},{"title":"Components","slug":"components","items":[{"title":"Overview","href":"/components"},{"title":"Animations","items":[{"title":"Tag","href":"/components/animations/tag"}]}]},{"title":"Guides","slug":"guides","items":[{"title":"Getting Started","href":"/guides"},{"title":"3dAnimations","items":[{"title":"Tag","href":"/guides/tag"}]}]}]};
