
// This file is autogenerated by scripts/build-preview-imports.ts
// Do not edit this file directly.
import type { DocsConfig } from "@/types/docs";

export const docsConfig: DocsConfig = {"nav":[{"title":"Getting Started","slug":"docs","items":[{"title":"Installation","href":"/docs/installation"},{"title":"Introduction","href":"/docs/introduction"}]},{"title":"Components","slug":"components","items":[{"title":"Overview","href":"/components"},{"title":"Animations","items":[{"title":"Tag","href":"/components/animations/tag"}]}]}]};
